[package]
name = "sim"
description = "Game physics simulation stuff"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
assets = { workspace = true }
rapier3d = { workspace = true }
log = { workspace = true }