[package]
name = "car-game-sim"
description = "Game physics simulation stuff"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
car-game-assets = { workspace = true }
car-game-utils = { workspace = true }
rapier3d = { workspace = true }
log = { workspace = true }
noise = "0.9"
winit = { workspace = true } 