[package]
name = "obj"
description = ".OBJ file reading utilities"
authors.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
log = { workspace = true }
